### ISSUE TITLE
(gifter-labo) 角度指定のorb.rollをラッピング

### ISSUE THREAD

**Issue by shundroid** [yammmt/Sphero-Auto-Pilot#10]
まだ角度を習っていない子供もいるので、
orb.roll()時の角度を言葉で表せられるようにしたい。

**Comment by yammmt** [comment]
お疲れ様です！
これは修正されてそうなので、 close で大丈夫ですかね？？

**Comment by shundroid** [comment]
Close し忘れてました。すみません。
しておきますー
