### ISSUE TITLE
逆方向に行った時、差が 90°より大きく、90°回転したとなってしまう

### ISSUE THREAD

**Issue by shundroid** [yammmt/Sphero-Auto-Pilot#11]
#2

説明しづらいな・・。

**Comment by yammmt** [comment]
お疲れ様です。
実行結果の

```
yawAngle: [ -149 ]
yawAngle: [ -165 ]
yawAngle: [ 178 ]
yawAngle: [ 165 ]
```

この真ん中部分の値が飛んでいる箇所のことです？？

**Comment by shundroid** [comment]
返信遅れましてすみません。
磁気センサーの話なのですが、
その場回転したとき、慣性とかで逆の方向に回ることがあります。
その時、90°以上曲がったとなってしまうのですが、
これは、「曲がった」と認識するとき、90° から 180°の範囲としたら、
できるようになりました。変更済みです。
Issue に更新するの忘れていました。すみませんでした。

close させていただきます。
