### ISSUE TITLE
gifter-labo ブランチで、loop 関数いる？

### ISSUE THREAD

**Issue by shundroid** [yammmt/Sphero-Auto-Pilot#15]
ぶつかった時にー ってのは、collision つかうし・・
となると逆に混乱するしいらないのでは・・

**Comment by yammmt** [comment]
むしろ loop 関数は backside.move(100, "前") とかで固定されていまうんですよね。
衝突発生時に一時的に色を変えて、次の loop で色を戻すという処理を書くには残っていた方が楽ではあると思います。

**Comment by shundroid** [comment]
そうですねーー。
色の処理は、
のような関数を用意して、一定時間後に戻せるようにラップしてみます。

``` js
backside.color("yellow", 1000);
```

引数は、`色, ミリ秒数` で、第二引数に色を適用する時間を指定してあげればいい気がします。

対象年齢的に、ミリ秒はきついですかね？

**Comment by yammmt** [comment]
お疲れ様ですー
ミリ秒のことは気付きませんでしたが、確かに面倒かもしれませんね。。
確かに単位はミリでなく秒になるようにラップしてあげた方が親切な気がします。

**Comment by shundroid** [comment]
わかりましたー。
では秒で指定できるようにラップしますね。

**Comment by shundroid** [comment]
#20 #16 ラップしました。

**Comment by yammmt** [comment]
お疲れ様です！
すると、色替えに関してはこれでうまくいっているのですが、
loop 関数はどうしましょうかね。

方向転換後に結局 roll を投げなくてはならないので、 Sphero の速度を弄れるという意味では、
個人的には残しておいたほうが良いような気がします。

**Comment by shundroid** [comment]
お返事ありがとうございます。

方向転換後に結局 roll を投げるというのは、
方向転換に roll を投げると思うので、`main.js` の `collision()` 内でできそうな感じです。

僕が思っているのは、次のような感じです。

メリット
- Lチカ的なことで、動作確認できる。
  - チュートリアルの最初のほうで使えるかも
  - orb.roll に関しては秒で指定するのは・・・ ( #13 )

デメリット
- 1つ loop という概念が増えちゃって、わかりにくくなるかも

やっぱり残しておいたほうがいいですか。

**Comment by yammmt** [comment]
うーん、とすると loop 抜きの方が説明が楽な気がしますね。。。
当日の説明員らしき方々にもちょっと意見を求めたいような気がやっぱりします。

あるいは、ブランチ生やして実装して見比べてみても良いのかもしれません。ちょっと時間かかってしまいますが…

**Comment by shundroid** [comment]
そうですね。
仰るとおり、ブランチ分けてやってみるのがいいかと思いました。
やってみますー！

**Comment by shundroid** [comment]
できましたー。
ブランチ作ったのですが、
新しいブランチのプルリクが多分できないので、
yammmt さん側で、ブランチだけ作ってもらっていいですか。
そしたらプルリク投げますー :+1:

**Comment by yammmt** [comment]
お疲れ様です。

ブランチ分けました。プルリクお願いしますー

**Comment by shundroid** [comment]
プルリク投げましたー
#21 です。おねがいします。

**Comment by shundroid** [comment]
> お疲れ様ですー作業ありがとうございます！
> 
> 単純に loop 関数を全消ししてしまうと、 move などの命令も一度しか呼ばれず、
> 自動操縦がうまくできないような気もするのですが、大丈夫です？？

Spheroの操縦に関しては、
ぶつかった時に送られる、collision 関数を用意してありますので、
そちらで move などの命令はできると思います。

逆に、loop 関数で move などの処理を行うと、
#13 の問題で、余計混乱してしまいそうです。
もし、loop 関数で move する場合は、
通信されているかをチェックするため、
命令を実行する前に、orb.ping をしなければならなくなります。

「ぶつかったら動かす」というプログラムでは、
loop 関数はいらないと思います。

やはり、迷路を解くアルゴリズムとして
いりますでしょうか・・。

また、今僕のパソコンでorb.roll をすると、
数秒後になぜか止まるというバグが発生しています。
もしかして、自動操縦ができないとはこのことでしょうか。
この場合は、backside.move でラップできそうです :+1:

**Comment by yammmt** [comment]
お疲れ様ですー

> orb.roll が数秒後に止まる

プログラム見た感じ、 orb.roll が function connect() 以外では呼ばれていないので、
最初に接続成功して呼ばれる一度しか反応していないのでは？と思います。
(プルリク #21 のコメントもここへの懸念でした。。) 

おっしゃる通り、 backside 側で loop 関数を回してあげると良いような気がします。

**Comment by shundroid** [comment]
そうでしたか～。
orb.roll に関してですが、確かに function connect() でのみ呼びだされています。
しかし、ストップする処理もしていないのに、
勝手に数秒後に止まるのは仕様なのかもなーと思います。

では backside 側で 数秒後に止まらないように、
ラップしておきますー

**Comment by shundroid** [comment]
コミットしましたー
プルリクが閉じられていないので、既存のプルリクに追加されたっぽいです。
動作確認済みです。よろしくおねがいします :+1:

**Comment by yammmt** [comment]
お疲れ様です。
マージします。訂正ありがとうございます！

orb.roll に関してですが、これは継続的に命令するものではなく、
一度だけ指定された方向に指定されただけの加速度を与えて Sphero を動かすものだと思いますー
node を直で起動し、 connect して roll を一度投げるとすぐに停止するので、多分そうです。

**Comment by shundroid** [comment]
そうなんですか！！確認ありがとうございます。
それじゃあ、仕様ですね。
加速度を与えるというのは、前も仰っていた気がしますが、
数秒後に止まる問題と、かみ合いませんでした・・！ありがとうございます！！

迷路で使うときは、継続的に投げたほうがいいっぽいですね。

**Comment by yammmt** [comment]
ですね。

とりあえずこれは解決したっぽいので、 close しておきます。
お疲れ様でした！
