### ISSUE TITLE
backside.color で、色を変える時間を指定。

### ISSUE THREAD

**Issue by shundroid** [yammmt/Sphero-Auto-Pilot#16]
orb.getColor() と、orb.color を組み合わせればできそう。
#15

**Comment by shundroid** [comment]
単位は秒で行きます。

**Comment by shundroid** [comment]
できました。

``` js
backside.color(orb, "色", 秒数);
```

秒数は、色を変更する前に戻すまでの時間です。
秒数を指定しないと、色を戻さないようにもしておきました。

**Comment by yammmt** [comment]
お疲れ様ですー
マージしました。ありがとうございます！
