### ISSUE TITLE
やべ。gifter-labo ブランチ、競合しちゃった。

### ISSUE THREAD

**Issue by shundroid** [yammmt/Sphero-Auto-Pilot#17]
すみません。
自分のコミットとyammmtさんのコミット(ローカルとリモート)
がついに gifter-labo ブランチで競合してしまいました。
#16 とか #5 とかやっていて、プルリクできるようにしたのですが・・

ちょっとこの解決で時間かかりそうです。初めてなので・・。

同じような機能とか実装しているかもしれないので、
マージするときの差分とかをここの Issue に上げていきます。

よろしくおねがいします。

**Comment by shundroid** [comment]
解決するためのプルリク送りましたー

**Comment by yammmt** [comment]
確認、マージしました。修正ありがとうございます！
