### ISSUE TITLE
https://github.com/comozilla で本リポジトリ管理しませんか？

### ISSUE THREAD

**Issue by dadaa** [yammmt/Sphero-Auto-Pilot#22]
理由としては以下のような感じです．
- コモジラ関連のプロジェクトを集約しておくと後々嬉しいかと
- ぼくもできるかぎりソースコードのレビューを行いたい
  ご検討くださいませー

**Comment by shundroid** [comment]
yammmt さんの活動の部分もあるので、
gifter-labo、gifter-labo(non-loop) ブランチだけでも移行するみたいなのがベストかと思います。

**Comment by yammmt** [comment]
お疲れ様です！  
言われてみればおっしゃる通りかと思います。ご指摘ありがとうございます。

@shundroid さんのおっしゃる通り、移す対象は少し絞った方が良いかもしれませんね。  
レポジトリ名を Sphero-Maze-Wakuwaku として、その二つのブランチだけ作ってみましょうか？

**Comment by shundroid** [comment]
そうしましょう！
やろうとしたのですが、権限がないっぽいので、リポジトリ作れないっぽいです。
時間的にパソコンをシャットダウンさせなければならないので、作ってもらっていいですか。
よろしくおねがいします。

**Comment by yammmt** [comment]
現在の Sphero-wakuwaku と内容が被ってしまいますね。
あちらは案内所的な、 README 的なものとして放置して、新たにレポジトリを作って管理するのが最も手っ取り早そうですが、それで大丈夫でしょうか？
コミットログが抜けてしまうような気がしているんですが、どうなんでしょう。

あるいは、レポジトリの移管であれば、[実例](http://mtoyoshi.hateblo.jp/entry/2013/06/25/171812) を参照にすれば良さそうです。

**Comment by dadaa** [comment]
新しく作っちゃって良いと思います
のちに Sphero-wakuwaku の内容を統合したら良いかなと

少なくともフォークだとコミットログも引き継げると思いますよん

**Comment by shundroid** [comment]
おはようございます。
仰るとおり、コミットログを引き継ぐなら（ぼくもそうしたいです）、
その二つのブランチだけ作るではなく、
フォークとか `git remote add` とかでリポジトリを移動してから、
その二つのブランチ以外を消すのがいいのかなーと思います。

**Comment by dadaa** [comment]
フォーク後に不必要なブランチの削除に賛成ですー

**Comment by yammmt** [comment]
comozilla/Sphero-Auto-Pilot にフォーク致しました。ご意見ありがとうございます！
ブランチは gifter-labo と gifter-labo(non-loop) が残っておりますが、
当日に non-loop 版を使用する予定であるなら、 non-loop を master にマージした方が良いかもしれませんね。

issue は引き続きフォーク元のこっちに立つみたいですね。

**Comment by shundroid** [comment]
> issue は引き続きフォーク元のこっちに立つみたいですね。

そうですねー。
作ったあとですみませんが、
フォークでなく、git remote add ならば、新しいリポジトリを単体で作ることになるので、
Issue も、comozilla の方に立てることができるようになりますねー。
まあ、過去に議論したこととかの引き継ぎはできないので、
Issue だけこちらでもいいかなーと

**Comment by dadaa** [comment]
issue 新しく作られないのか，，
git remote add の方が良いかもですね
これでもコミットログは引き継げるみたいですし．

**Comment by shundroid** [comment]
そうっぽいです。

フォーク元を切り離す方法とかありますかね。
リポジトリ作りなおすしかないのかなー。

**Comment by yammmt** [comment]
ご意見ありがとうございます！
とりあえず git remote add で master 、 gifter-labo 、 gifter-labo(non-loop) を以下に push しました：
https://github.com/comozilla/Sphero-Maze-Wakuwaku
また、紛らわしい + 使わなそうなのでフォークした方のレポジトリは消した方が良いような気がしますが、いかがでしょう。

新たな issue は comozilla 側に立てれば良いと思いますが、
既存の issue は手作業でむこうに移しましょうか。

このあと少し私用があるので、他に作業があれば明日朝日が昇るまでに確認致します。
よろしくお願い致します。

**Comment by dadaa** [comment]
フォークした方を削除しちゃっていいかと思いますー
これを Sphero-Maze-Wakuwaku をいじっていきましょ
これまで通り pull request してやっていきましょ
ぼくもマージとソースコードレビューをお手伝いできればと思います．

**Comment by shundroid** [comment]
リポジトリが、git pull してないせいか、ちょっと古かったっぽいので、
最新版にするプルリク、comozilla の方に送りましたー。
確認よろしくおねがいします :+1:

**Comment by yammmt** [comment]
ご意見ありがとうございます。
comozilla 側の Sphero-Auto-Pilot を削除致しました。

@shundroid さんのプルリクに関しては、 comozilla 側で議論中のようなので、
この件はとりあえずここで close とさせて頂きます。ありがとうございました。
次回作にご期待下さい。
